Repository rollbar/rollbar-php, pull requests merged in 2021-06, with the labels that each got.

#530 feat: v3.0.0-RC2
  CHANGELOG.md
  src/Payload/Notifier.php
  tests/NotifierTest.php
Labels: Rank: 1 - Critical

#526 refac: remove unreachable version compare branches
  src/DataBuilder.php
  src/Defaults.php
  tests/DataBuilderTest.php
  tests/DefaultsTest.php
Labels: Rank: 3 - Minor, Status: 3 - Construction, Type: Maintenance

#529 Remove throwable anachronism
  src/Config.php
  src/DataBuilder.php
  src/DataBuilderInterface.php
  src/RollbarLogger.php
  tests/FakeDataBuilder.php
Labels: Rank: 3 - Minor, Status: 3 - Construction, Type: Maintenance

#531 fix: typo in output error message
  src/RollbarLogger.php
Labels: Rank: 4 - Low, Status: 3 - Construction, Type: Maintenance

#532 Fix broken performance tests
  tests/Performance/TestHelpers/EncodedPayload.php
  tests/Performance/TruncationTest.php
  tests/Truncation/StringsStrategyTest.php
Labels: Rank: 3 - Minor, Status: 4 - Verified, Type: Bug

#494 Replace Whitelist with Safelist
  src/Config.php
  src/Scrubber.php
  tests/RollbarLoggerTest.php
  tests/ScrubberTest.php
Labels: Rank: 4 - Low, Status: 2 - Accepted, Type: Enhancement
