Repository rollbar/rollbar-php, pull requests merged in 2021-05, with the labels that each got.

#500 Remove Monolog's StreamHandler from rollbar-php
  src/RollbarLogger.php
Labels: Rank: 4 - Low, Status: 2 - Accepted, Type: Maintenance

#521 Annotate function signatures
  src/Config.php
  src/DataBuilder.php
  src/DataBuilderInterface.php
  src/Defaults.php
  src/ErrorWrapper.php
  src/FilterInterface.php
  src/Handlers/AbstractHandler.php
  src/Handlers/ErrorHandler.php
  src/Handlers/ExceptionHandler.php
  src/Handlers/FatalHandler.php
  src/LevelFactory.php
  src/Payload/Body.php
  src/Payload/ContentInterface.php
  src/Payload/Context.php
  src/Payload/Data.php
  src/Payload/EncodedPayload.php
  src/Payload/ExceptionInfo.php
  src/Payload/Frame.php
  src/Payload/Level.php
  src/Payload/Message.php
  src/Payload/Notifier.php
  src/Payload/Payload.php
  src/Payload/Person.php
  src/Payload/Request.php
  src/Payload/Server.php
  src/Payload/Trace.php
  src/Payload/TraceChain.php
  src/Response.php
  src/ResponseHandlerInterface.php
  src/Rollbar.php
  src/RollbarJsHelper.php
  src/RollbarLogger.php
  src/Scrubber.php
  src/ScrubberInterface.php
  src/Senders/AgentSender.php
  src/Senders/CurlSender.php
  src/Senders/FluentSender.php
  src/Senders/SenderInterface.php
  src/TransformerInterface.php
  src/Truncation/AbstractStrategy.php
  src/Truncation/FramesStrategy.php
  src/Truncation/IStrategy.php
  src/Truncation/MinBodyStrategy.php
  src/Truncation/RawStrategy.php
  src/Truncation/StringsStrategy.php
  src/Truncation/Truncation.php
  src/Utilities.php
  tests/ConfigTest.php
  tests/ErrorWrapperTest.php
  tests/TestHelpers/MalformedPayloadDataTransformer.php
  tests/VerbosityTest.php
Labels: Rank: 2 - Major, Status: 3 - Construction, Type: Maintenance

#522 fix: missing URL encoding of UUID in occurrences
  src/Response.php
  tests/ResponseTest.php
Labels: Rank: 4 - Low, Status: 3 - Construction, Type: Bug

#523 fix: Propagate PR #500 to 2.x series.
  src/RollbarLogger.php
Labels: Rank: 4 - Low, Status: 3 - Construction, Type: Maintenance

#524 accessToken is a string
  src/FilterInterface.php
  src/Payload/Payload.php
  src/RollbarLogger.php
  src/Senders/AgentSender.php
  src/Senders/CurlSender.php
  src/Senders/FluentSender.php
  src/Senders/SenderInterface.php
Labels: Rank: 2 - Major, Status: 3 - Construction, Type: Maintenance
