Repository rollbar/rollbar-php, pull requests merged in 2023-04, with the labels that each got.

#615 Backport of #614 Added response status code to verbose log message.
  src/RollbarLogger.php
  tests/VerbosityTest.php
Labels: Type: Enhancement

#616 Added missing CI workflow for v3.x
  .github/workflows/ci-3.x.yml
Labels: Type: Maintenance

#614 Fixed #613 Added response status code to verbose log message.
  src/RollbarLogger.php
  tests/VerbosityTest.php
Labels: Type: Enhancement

#623 Fixed #617 `RollbarLogger:log()` not compatible with psr/log 1
  src/RollbarLogger.php
  tests/TestHelpers/StdOutLogger.php
Labels: Type: Bug

#625 chore: add phpunit 10 result folder to gitignore
  .gitignore
Labels: Type: Maintenance

#626 Fixed test helper method `ArrayLogger:log()` psr/log 1 compatability
  tests/TestHelpers/ArrayLogger.php
Labels: Type: Bug

#627 Updated test dependencies to fix generated mock class type annotation error
  composer.json
Labels: Type: Bug, Type: Maintenance

#628 Fixed the CI status badge in the README.md file.
  README.md
Labels: Type: Maintenance

#624 chore: add ci tests for --prefer-lowest
  .github/workflows/ci-3.x.yml
  .github/workflows/ci.yml
Labels: Type: Maintenance

#619 chore: fix tests for performance test-suite
  tests/Performance/MassivePayload.php
  tests/Performance/TestHelpers/Truncation.php
  tests/Performance/TruncationTest.php
Labels: Type: Maintenance

#621 Feat: allow phpunit 10
  composer.json
  phpunit.xml
  tests/BaseRollbarTest.php
  tests/ConfigTest.php
  tests/DataBuilderTest.php
  tests/FakeLog.php
  tests/Handlers/ErrorHandlerTest.php
  tests/Handlers/ExceptionHandlerTest.php
  tests/JsHelperTest.php
  tests/LevelFactoryTest.php
  tests/NotifierTest.php
  tests/RollbarLoggerTest.php
  tests/RollbarTest.php
  tests/ScrubberTest.php
  tests/Truncation/FramesStrategyTest.php
  tests/Truncation/MinBodyStrategyTest.php
  tests/Truncation/StringsStrategyTest.php
  tests/Truncation/TruncationTest.php
Labels: Type: Maintenance
