Repository rollbar/rollbar-php, pull requests merged in 2023-01, with the labels that each got.

#588 Updated the typing and comments for the `ResponseHandlerInterface`
  src/Config.php
  src/ResponseHandlerInterface.php
  src/RollbarLogger.php
Labels: Type: Maintenance

#591 Added typing / comments to the `ScrubberInterface` and `Scrubber` class
  src/Config.php
  src/Payload/Payload.php
  src/Scrubber.php
  src/ScrubberInterface.php
  tests/RollbarLoggerTest.php
  tests/ScrubberTest.php
  tests/TestHelpers/MalformedPayloadDataTransformer.php
Labels: Type: Maintenance

#587 Added typing / comments to the `FilterInterface` and removed the token argument
  src/Config.php
  src/FilterInterface.php
  src/RollbarLogger.php
  tests/ConfigTest.php
  tests/VerbosityTest.php
Labels: Type: Maintenance

#592 Added typing / comments to the `SenderInterface`
  src/Senders/AgentSender.php
  src/Senders/CurlSender.php
  src/Senders/FluentSender.php
  src/Senders/SenderInterface.php
  tests/ConfigTest.php
Labels: Type: Maintenance

#593 Updated the `TransformerInterface`
  src/Config.php
  src/RollbarLogger.php
  src/TransformerInterface.php
  tests/TestHelpers/MalformedPayloadDataTransformer.php
Labels: Type: Maintenance

#459 Fix incorrect array encoding in config produced by RollbarJsHelper
  src/RollbarJsHelper.php
  tests/JsHelperTest.php
Labels: Type: Bug, Status: 3 - Construction, Rank: 2 - Major

#595 Fixed #469 Added `requireAccessToken()` method to senders
  src/Config.php
  src/Senders/AgentSender.php
  src/Senders/CurlSender.php
  src/Senders/FluentSender.php
  src/Senders/SenderInterface.php
  tests/ConfigTest.php
  tests/FluentTest.php
Labels: Type: Bug
